### ISSUE TITLE
ModuleNotFoundError: `std_msgs` at roslaunch

### ISSUE THREAD

**Issue by orestiskapar** [ros-melodic-arch/ros-melodic-std-msgs#1] opened 2020-03-22 14:11 UTC
Launching throws a `ModuleNotFoundError: No module named 'std_msgs'`. 
```
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/roslaunch", line 34, in <module>
    import roslaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/__init__.py", line 62, in <module>
    from .scriptapi import ROSLaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/scriptapi.py", line 42, in <module>
    import roslaunch.parent
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/parent.py", line 54, in <module>
    import roslaunch.server
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/server.py", line 79, in <module>
    from rosgraph_msgs.msg import Log
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/__init__.py", line 2, in <module>
    from ._Log import *
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/_Log.py", line 8, in <module>
    import std_msgs.msg
ModuleNotFoundError: No module named 'std_msgs'
```
Updating to 0.5.13 did indeed solve it as claimed by @avisy in the [AUR page](https://aur.archlinux.org/packages/ros-melodic-std-msgs/).
> update to ros-melodic-std-msgs 0.5.13 can solve it.

**Comment by jwhendy** [comment] 2020-03-22 18:17
I just did this with no errors:

```
$ roslaunch turtle_tf2 turtle_tf2_demo.launch
```

Could this be related to your other bug [here](https://github.com/ros-melodic-arch/ros-melodic-actionlib-msgs/issues/1)? For example, can you do this?
```
$ rosmsg info std_msgs/Int32
```

Or this?
```
$ find /opt/ros/melodic/ -iname std_msgs
/opt/ros/melodic/lib/python3.8/site-packages/std_msgs
/opt/ros/melodic/share/roseus/ros/std_msgs
/opt/ros/melodic/share/gennodejs/ros/std_msgs
/opt/ros/melodic/share/common-lisp/ros/std_msgs
/opt/ros/melodic/share/std_msgs
/opt/ros/melodic/include/std_msgs
```

Or this:
```
$ pacman -Qo /opt/ros/melodic/lib/python3.8/site-packages/std_msgs
/opt/ros/melodic/lib/python3.8/site-packages/std_msgs/ is owned by ros-melodic-std-msgs 0.5.12-1
```

I wonder if you have a split python3.7 vs. python3.8 system and will find that `std_msgs` is living in python3.7.

**Comment by orestiskapar** [comment] 2020-03-22 19:12
The example loads without errors (though arrow keys don't move the turtle?). Perhaps the other issue is indeed related, `rosmsg` fails with another `ModuleNotFoundError` for Crypto, but it's not in either `/opt/ros/melodic/lib/python3.7/site-packages/` or `/opt/ros/melodic/lib/python3.8/site-packages/`.
```
➜  ~ rosmsg info std_msgs/Int32
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/rosmsg", line 35, in <module>
    rosmsg.rosmsgmain()
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosmsg/__init__.py", line 754, in rosmsgmain
    sys.exit(rosmsg_cmd_show(ext, full, command))
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosmsg/__init__.py", line 582, in rosmsg_cmd_show
    import rosbag
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosbag/bag.py", line 53, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'
```
```
➜  ~ find /opt/ros/melodic -iname std_msgs      
/opt/ros/melodic/include/std_msgs
/opt/ros/melodic/lib/python3.8/site-packages/std_msgs
/opt/ros/melodic/share/std_msgs
/opt/ros/melodic/share/roseus/ros/std_msgs
/opt/ros/melodic/share/common-lisp/ros/std_msgs
/opt/ros/melodic/share/gennodejs/ros/std_msgs
```
```
➜  ~ pacman -Qo /opt/ros/melodic/lib/python3.8/site-packages/std_msgs 
/opt/ros/melodic/lib/python3.8/site-packages/std_msgs/ is owned by ros-melodic-std-msgs 0.5.13-1
```
It is under `python3.8` now, but this is after I updated to `0.5.13-1`, as I said in the initial comment.

**Comment by jwhendy** [comment] 2020-03-22 22:32
> It is under python3.8 now, but this is after I updated to 0.5.13-1, as I said in the initial comment.

Sure, but mine is under `python3.8` and I'm on `0.5.12`. This is an issue, so the point is to find the underlying cause, not just haphazardly why `0.5.13` magically fixes this. If we don't understand the mechanism, how do we learn anything for, say, when `python3.9` comes out?

Not to  mention, you're coming here because you've found *one* side-effect... what if something deeper is going on? You can now do trivial activities like `roscore`, but might find that other parts of your ecosystem are just waiting not to be found due to the same overall issue.

I'd like to _solve_ this, not just find an accidental fix and tell everyone to to that.

If you would like to help solve this (I can't since I don't have an affected system), I'd love your help. Otherwise we can just close this as non-reproducible.

**Comment by jwhendy** [comment] 2020-03-22 23:27
This auto-closed when I merged the update, but I want it to stay open until we find the root cause, if possible.

**Comment by acxz** [comment] 2020-03-23 03:12
I'll go ahead and remove the labels tho as this package is not out of date, nor can we reproduce the runtime error on the latest stable release of this package.

**Comment by bionade24** [comment] 2020-03-23 09:10
Will close this issue, as probably a rebuild or clean built packags from a repo would fix it, too.

**Closed as completed by bionade24** 2020-03-23 09:10 UTC
